Update pmss
A few cosmetic changes.

diff --git a/pmss b/pmss
--- a/pmss
+++ b/pmss
@@ -1,90 +1,100 @@
-#!/bin/bash
+#!/usr/bin/env bash
+printf "\033c"
+type scrot >/dev/null 2>&1 || { printf "\033c"; echo -e ""; echo -e '\E[1;32;49m'"A required pmss dependency \"Scrot\" is not present."; echo -e '\e[1;32;49m'"\"Scrot\" is available for almost all linux distros."; echo -e '\e[1;32;49m'"Please install \"scrot\" using your package manager."; echo -e ""; tput sgr0; exit 1; }
 DIR="${HOME}/Pictures/Screenshots"
-
-clear
-
 if [ ! -d "${DIR}" ]; then mkdir "${DIR}"; fi
-
 while true
 do
-
+tput sgr0
+echo -e '\E[1;32;49m'"** PMSS<>MENU *************************************************"
 echo -e ""
-echo -en '\e[0m'
-echo -e '\E[1;32;40m'"**********************************************************";
-echo -e '\E[1;32;40m'"****************                          ****************";
-echo -e '\E[1;32;40m'"                Poorman's ** Screenshooter";
-echo -e '\E[1;32;40m'"****************                          ****************";
-echo -e '\E[1;32;40m'"**********************************************************";
 echo -e ""
-echo -e '\E[1;32;40m'"Select One Of The Following Options,";
+echo -e '\E[1;32;49m'"** Select One Of The Following Options"
 echo -e ""
-echo -e '\E[1;32;40m'"Enter [E] To Take The Screenshot Of The Entire Screen";
-echo -e '\E[1;32;40m'"Enter [W] To Take The Screenshot Of Window In Focus";
-echo -e '\E[1;32;40m'"Enter [A] To Take The Screenshot Of Area Selected By Mouse";
-echo -e '\E[1;32;40m'"Enter [Q] To Exit";
-echo -en '\e[0m'
+echo -e '\E[1;32;49m'"** Enter \"E\" To Take The Screenshot Of The Entire Screen"
+echo -e '\E[1;32;49m'"** Enter \"W\" To Take The Screenshot Of Window In Focus"
+echo -e '\E[1;32;49m'"** Enter \"A\" To Take The Screenshot Of Area Selected By Mouse"
+echo -e '\E[1;32;49m'"** Enter \"Q\" To Exit"
 echo -e ""
-
-read option
-case "$option" in
-
-"E" | "e" )
-clear
+echo -e '\E[1;32;49m'"***************************************************************"
+echo -e ""
+tput sgr0
+read -er Options
+case "$Options" in
+"E" | "e")
+printf "\033c"
 DATE="$(date +%d%m%y-%H%M%S)"
 SHORT_NAME="Shot-${DATE}.png"
 NAME="${DIR}/${SHORT_NAME}"
-echo -e '\E[1;32;40m'"Minimize Terminal To Avoid It From Being Captured..";
+echo -e ""
+echo -e '\E[1;32;49m'"Minimize Terminal To Avoid It From Being Captured.."
+echo -e ""
 scrot -d10 -c "${NAME}"
-clear
-echo -e '\E[1;31;40m'"$SHORT_NAME Saved in '$DIR'";
+printf "\033c"
+echo -e ""
+echo -e '\E[1;31;49m'"$SHORT_NAME Saved in '$DIR'"
+echo -e ""
 xdg-open "${NAME}"
 continue
 ;;
-
-"W" | "w" )
-clear
+"W" | "w")
+printf "\033c"
 DATE="$(date +%d%m%y-%H%M%S)"
 SHORT_NAME="Shot-${DATE}.png"
 NAME="${DIR}/${SHORT_NAME}"
-echo -e '\E[1;32;40m'"Minimize Terminal And Bring The Window To Be Captured In Focus..";
+echo -e ""
+echo -e '\E[1;32;49m'"Minimize Terminal And Bring The Window To Be Captured In Focus.."
+echo -e ""
 scrot -u -d10 -b -c "${NAME}"
-clear
-echo -e '\E[1;31;40m'"$SHORT_NAME Saved in '$DIR'";
+printf "\033c"
+echo -e ""
+echo -e '\E[1;31;49m'"$SHORT_NAME Saved in '$DIR'"
+echo -e ""
 xdg-open "${NAME}"
 continue
 ;;
-
-"A" | "a" )
-clear
+"A" | "a")
+printf "\033c"
 DATE="$(date +%d%m%y-%H%M%S)"
 SHORT_NAME="Shot-${DATE}.png"
 NAME="${DIR}/${SHORT_NAME}"
-echo -e '\E[1;32;40m'"Draw A Rectangle On The Screen And Area Inside It Will Be Captured..";
+echo -e ""
+echo -e '\E[1;32;49m'"Draw A Rectangle On The Screen And Area Inside It Will Be Captured.."
+echo -e ""
 scrot -s "${NAME}"
-clear
-echo -e '\E[1;31;40m'"$SHORT_NAME Saved in '$DIR'";
+printf "\033c"
+echo -e ""
+echo -e '\E[1;31;49m'"$SHORT_NAME Saved in '$DIR'"
+echo -e ""
 xdg-open "${NAME}"
 continue
 ;;
-
-"Q" | "q" )
-clear
-echo -e '\E[1;32;40m'"Thanks.. Bye Bye..";
-sleep 3
-echo -en '\e[0m'
-clear
+"Q" | "q")
+printf "\033c"
+echo -e ""
+echo -e '\E[1;32;49m'"Bye.. Bye.."
+echo -e ""
+sleep 2
+printf "\033c"
+tput sgr0
 break
+exit 0
 ;;
-
-* )
-clear
-echo -e '\E[1;31;40m'"Incorrect Option Selected..";
-sleep 3
-echo -en '\e[0m'
-clear
+*)
+printf "\033c"
+echo -e ""
+echo -e '\E[1;31;49m'"\"$Options\" Is An Invalid Option!!!"
+echo -e ""
+echo -e '\E[1;31;49m'"Correct Options To Choose Are From E-W-A-Q"
+echo -e ""
+echo -e '\E[1;31;49m'"To Take The Screenshot Of The Entire Screen, Press \"E\" & Hit \"Enter\" Key"
+echo -e '\E[1;31;49m'"To Take The Screenshot Of Window In Focus, Press \"W\" & Hit \"Enter\" Key"
+echo -e '\E[1;31;49m'"To Take The Screenshot Of Area Selected By Mouse, Press \"A\" & Hit \"Enter\" Key"
+echo -e '\E[1;31;49m'"To Exit From PMSS, Press \"Q\" & Hit \"Enter\" Key"
+echo -e '\E[1;32;49m'""
+read -rsp $'Press Any Key To Return To PMSS MENU..\n' -n1
+printf "\033c"
 continue
 ;;
-
 esac
 done
-exit 0
